[2020-06-17 19:48:11,342] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v5.save_processed 2020-06-17T23:46:57.455943+00:00 [queued]>
[2020-06-17 19:48:11,353] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v5.save_processed 2020-06-17T23:46:57.455943+00:00 [queued]>
[2020-06-17 19:48:11,353] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:48:11,353] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-17 19:48:11,354] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:48:11,511] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-17T23:46:57.455943+00:00
[2020-06-17 19:48:11,514] {standard_task_runner.py:53} INFO - Started process 11756 to run task
[2020-06-17 19:48:11,749] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MIS_v5.save_processed 2020-06-17T23:46:57.455943+00:00 [running]> strx
[2020-06-17 19:48:11,758] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-17 19:48:12,522] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-17 19:48:12,710] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=MIS_v5, task_id=save_processed, execution_date=20200617T234657, start_date=20200617T234811, end_date=20200617T234812
[2020-06-17 19:48:21,217] {logging_mixin.py:112} INFO - [2020-06-17 19:48:21,217] {local_task_job.py:103} INFO - Task exited with return code 0
