[2020-06-03 19:35:30,211] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: python_test.check_file 2020-01-01T00:00:00+00:00 [queued]>
[2020-06-03 19:35:30,217] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: python_test.check_file 2020-01-01T00:00:00+00:00 [queued]>
[2020-06-03 19:35:30,217] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 19:35:30,217] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-03 19:35:30,217] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 19:35:30,381] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): check_file> on 2020-01-01T00:00:00+00:00
[2020-06-03 19:35:30,383] {standard_task_runner.py:53} INFO - Started process 19801 to run task
[2020-06-03 19:35:30,571] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: python_test.check_file 2020-01-01T00:00:00+00:00 [running]> strx
[2020-06-03 19:35:30,607] {logging_mixin.py:112} INFO - check_change 2020-01-01
[2020-06-03 19:35:30,607] {taskinstance.py:1145} ERROR - name 'sleep' is not defined
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/example_python.py", line 45, in check_change
    sleep(5)
NameError: name 'sleep' is not defined
[2020-06-03 19:35:30,636] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-03 19:35:40,079] {logging_mixin.py:112} INFO - [2020-06-03 19:35:40,078] {local_task_job.py:103} INFO - Task exited with return code 1
