[2020-06-18 13:32:12,148] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado_v3.save_processed 2020-06-18T17:24:50.403561+00:00 [queued]>
[2020-06-18 13:32:12,201] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado_v3.save_processed 2020-06-18T17:24:50.403561+00:00 [queued]>
[2020-06-18 13:32:12,201] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 13:32:12,201] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 13:32:12,202] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 13:32:12,246] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-18T17:24:50.403561+00:00
[2020-06-18 13:32:12,250] {standard_task_runner.py:53} INFO - Started process 21005 to run task
[2020-06-18 13:32:12,363] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sh_macerado_v3.save_processed 2020-06-18T17:24:50.403561+00:00 [running]> strx
[2020-06-18 13:32:12,414] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-18 13:32:12,445] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-18 13:32:12,541] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=sh_macerado_v3, task_id=save_processed, execution_date=20200618T172450, start_date=20200618T173212, end_date=20200618T173212
[2020-06-18 13:32:21,998] {logging_mixin.py:112} INFO - [2020-06-18 13:32:21,997] {local_task_job.py:103} INFO - Task exited with return code 0
