[2020-06-18 14:26:22,780] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sap_v2.save_processed 2020-06-18T18:26:12.388762+00:00 [queued]>
[2020-06-18 14:26:22,834] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sap_v2.save_processed 2020-06-18T18:26:12.388762+00:00 [queued]>
[2020-06-18 14:26:22,835] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 14:26:22,835] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 14:26:22,835] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 14:26:22,939] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-18T18:26:12.388762+00:00
[2020-06-18 14:26:22,943] {standard_task_runner.py:53} INFO - Started process 26428 to run task
[2020-06-18 14:26:23,048] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sap_v2.save_processed 2020-06-18T18:26:12.388762+00:00 [running]> strx
[2020-06-18 14:26:23,078] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-18 14:26:39,477] {python_operator.py:114} INFO - Done. Returned value was: save_processed
[2020-06-18 14:26:39,546] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=sap_v2, task_id=save_processed, execution_date=20200618T182612, start_date=20200618T182622, end_date=20200618T182639
[2020-06-18 14:26:42,829] {logging_mixin.py:112} INFO - [2020-06-18 14:26:42,829] {local_task_job.py:103} INFO - Task exited with return code 0
