[2020-06-18 21:49:39,623] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: recepcion.save_processed 2020-06-19T01:48:28.296830+00:00 [queued]>
[2020-06-18 21:49:39,730] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: recepcion.save_processed 2020-06-19T01:48:28.296830+00:00 [queued]>
[2020-06-18 21:49:39,730] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 21:49:39,730] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 21:49:39,730] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 21:49:39,764] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-19T01:48:28.296830+00:00
[2020-06-18 21:49:39,769] {standard_task_runner.py:53} INFO - Started process 20235 to run task
[2020-06-18 21:49:39,989] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: recepcion.save_processed 2020-06-19T01:48:28.296830+00:00 [running]> strx
[2020-06-18 21:49:40,065] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-18 21:49:40,163] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-18 21:49:40,239] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=recepcion, task_id=save_processed, execution_date=20200619T014828, start_date=20200619T014939, end_date=20200619T014940
[2020-06-18 21:49:49,473] {logging_mixin.py:112} INFO - [2020-06-18 21:49:49,473] {local_task_job.py:103} INFO - Task exited with return code 0
