[2020-06-24 20:01:26,528] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: mis.save_processed 2020-06-25T00:01:10.830105+00:00 [queued]>
[2020-06-24 20:01:26,642] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: mis.save_processed 2020-06-25T00:01:10.830105+00:00 [queued]>
[2020-06-24 20:01:26,643] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-24 20:01:26,643] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-24 20:01:26,643] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-24 20:01:26,673] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-25T00:01:10.830105+00:00
[2020-06-24 20:01:26,686] {standard_task_runner.py:53} INFO - Started process 16492 to run task
[2020-06-24 20:01:26,808] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: mis.save_processed 2020-06-25T00:01:10.830105+00:00 [running]> strx
[2020-06-24 20:01:26,840] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-24 20:01:28,728] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-24 20:01:28,826] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=mis, task_id=save_processed, execution_date=20200625T000110, start_date=20200625T000126, end_date=20200625T000128
[2020-06-24 20:01:36,380] {logging_mixin.py:112} INFO - [2020-06-24 20:01:36,380] {local_task_job.py:103} INFO - Task exited with return code 0
