[2020-06-18 22:12:55,427] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado.save_processed 2020-06-19T02:12:37+00:00 [queued]>
[2020-06-18 22:12:55,496] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado.save_processed 2020-06-19T02:12:37+00:00 [queued]>
[2020-06-18 22:12:55,496] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:12:55,496] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 22:12:55,496] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:12:55,526] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-19T02:12:37+00:00
[2020-06-18 22:12:55,530] {standard_task_runner.py:53} INFO - Started process 27872 to run task
[2020-06-18 22:12:55,714] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sh_macerado.save_processed 2020-06-19T02:12:37+00:00 [running]> strx
[2020-06-18 22:12:55,785] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-18 22:12:55,810] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-18 22:12:55,916] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=sh_macerado, task_id=save_processed, execution_date=20200619T021237, start_date=20200619T021255, end_date=20200619T021255
[2020-06-18 22:13:05,373] {logging_mixin.py:112} INFO - [2020-06-18 22:13:05,372] {local_task_job.py:103} INFO - Task exited with return code 0
