[2020-06-08 09:30:29,194] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: python_test.save_raw_file 2019-08-08T00:00:00+00:00 [queued]>
[2020-06-08 09:30:29,204] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: python_test.save_raw_file 2019-08-08T00:00:00+00:00 [queued]>
[2020-06-08 09:30:29,204] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 09:30:29,204] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-08 09:30:29,204] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 09:30:29,352] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_raw_file> on 2019-08-08T00:00:00+00:00
[2020-06-08 09:30:29,355] {standard_task_runner.py:53} INFO - Started process 1856 to run task
[2020-06-08 09:30:29,542] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: python_test.save_raw_file 2019-08-08T00:00:00+00:00 [running]> strx
[2020-06-08 09:30:29,556] {logging_mixin.py:112} INFO - save_raw_file 2019-08-08
[2020-06-08 09:30:34,562] {python_operator.py:114} INFO - Done. Returned value was: save_raw_file
[2020-06-08 09:30:34,713] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=python_test, task_id=save_raw_file, execution_date=20190808T000000, start_date=20200608T133029, end_date=20200608T133034
[2020-06-08 09:30:39,062] {logging_mixin.py:112} INFO - [2020-06-08 09:30:39,061] {local_task_job.py:103} INFO - Task exited with return code 0
